version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gig-insure-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: giguser
      POSTGRES_PASSWORD: gigpassword
      POSTGRES_DB: giginsure
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
